# Generated by Django 6.0.4 on 2026-05-06 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listacompra',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('lista', 'produto')},
        ),
        migrations.RemoveField(
            model_name='listacompra',
            name='name',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.AddField(
            model_name='item',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listacompra',
            name='nome',
            field=models.CharField(default='produto neve', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='produto', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='novo', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='123456', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='listacompra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='item',
            table='itens',
        ),
        migrations.AlterModelTable(
            name='listacompra',
            table='listas_compras',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produtos',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='compras.categoria'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='item',
            name='valor',
        ),
    ]
